/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BatchReq {
  market: string
  cancel?: Array<string>
  place?: Array<JsOrder>
  snapLevels?: number
}

export declare function cancel(symbol: string, orderId: string): boolean

export declare function cancelAllBySocket(symbol: string, socketId: string): number

export declare function cancelAllBySocketGlobal(socketId: string): number

export declare function createBook(symbol: string): boolean

export declare function debugSocket(symbol: string, socketId: string): string

export declare function dropBook(symbol: string): boolean

export declare function edit(symbol: string, orderId: string, newQty?: number | undefined | null, newPrice?: number | undefined | null): boolean

export declare function getOpenOrdersBySocket(socketId: string, symbol: string): string

export declare function getOrderHistoryBySocket(market: string, socketId: string, limit?: number | undefined | null): string

export interface JsOrder {
  uuid: string
  side: string
  price: number
  amount: number
  socketId?: string
}

export declare function setExecSink(cb: (arg?: unknown) => unknown): void

export declare function setStpfPolicy(policy: string): boolean

export declare function snapshot(symbol: string, depth?: number | undefined | null): string

export declare function stats(symbol: string): string

export declare function submit(symbol: string, order: JsOrder): string

export declare function submitBatch(req: BatchReq): string
